# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a057d077b9c13da829794f08824f24a1fcd5ad8a142d45c391573889f1ba46b32154c65d0bfb61529ee3fae520e703992b66c01164aa9bbba55726c9d8848848

test:
  secret_key_base: 526b052a9a21cb4f6df62eedb1cbec92dbb5a531812bbf1fe96fd1b9ffeb486b4c6872a55611ef3b795958d32d9fbf529c377299ac675a1fc5921f6e1d862caa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
